### ISSUE TITLE
Body data incomplete

### ISSUE THREAD

**Issue by tomazk8** [StefH/NETStandard.HttpListener#1]
Hi

I tried HttpListener in the UWP application to receive JSON in the HTTP request body. I found out that whenever I send just a little bit more data I get only the part of the JSON in the body. With the wireshark I can see that HTTP request is sent via many TCP packets so I assume that HTTPListener did not combine the packets back into one request, but only took the first one.

Regards
Tomaz

**Comment by StefH** [comment]
I will take a look.

- Do you have the same issue with the netstandard?
- And can you provide some code example?

**Comment by tomazk8** [comment]
I am trying now again with different HTTP servers and different HTTP clients and I get exactly the same behavior. I am running the server on the Raspberry Pi 3 and it works as long as HTTP body is very small. But with json in the body of size 4kb is already too much. I can see in Wireshark it is being sent in 4 packets. I have currently no idea why this happens but it probably means it's not a bug in your library.

**Comment by tomazk8** [comment]
I think I found it. On the socket, the property DontFragment was set to true which means it will discard all additional fragments. That's probably why I get partial content in the request. I will try to set it to false today and see if it helps. I believe it's definitely not a bug in your library ;).

**Comment by tomazk8** [comment]
No, sorry, didn't help. It's exactly the same :(. I don't know where to search for the problem. Strange is that sometimes it actually works with the same content size, but sometimes not.

**Comment by tomazk8** [comment]
Hurey, I found it :). There was a bug in your code. When reading data from request's input stream, you where reading it only once. But sometimes read method on the stream returned only part of the data so you have to read until content length is read. Here is a change in your code to fix it (HttpListenerRequest.cs, line 68):

change this:
`await reader.ReadAsync(buffer, 0, contentLength);`

into this:
`int amount = 0;

while (amount < contentLength)
{
    int l = await reader.ReadAsync(buffer, amount, contentLength - amount);

    if (l == 0)
        throw new Exception("Reading from request stream returned less data as expected.");

    amount += l;
}`

Regards
Tomaz

**Comment by StefH** [comment]
I think that
```c#
await reader.ReadBlockAsync(buffer, 0, contentLength);
```
Will also work, according to documentation on :
https://msdn.microsoft.com/en-us/library/system.io.streamreader.readblockasync(v=vs.110).aspx

Can you verify that ?

**Comment by tomazk8** [comment]
Yes, confirmed. This also works.

**Comment by StefH** [comment]
OK.

I'm trying to build a unit-test to test this.

**Comment by StefH** [comment]
See new NuGet.
