### ISSUE TITLE
Bug: Circular reference StringBuilder

### ISSUE THREAD

**Issue by Jimmy062006** [StefH/NETStandard.HttpListener#10]
It seems I'm able to generate a memory leak with Circular references for a StringBuilder in your code.

Memory usage goes threw the roof

[Memory Usage 1](https://cdn.discordapp.com/attachments/289730931064045568/353122087029833728/unknown.png)

To the point it crashes the system

[Memory Usage 2](https://cdn.discordapp.com/attachments/289730931064045568/353124572872179712/unknown.png)

I've traced this back to StringBuilder and can confirm that it is creating a Circular reference

[Circular Reference 1](https://cdn.discordapp.com/attachments/289730931064045568/353124348514533388/unknown.png)

[Circular Reference 2](https://cdn.discordapp.com/attachments/289730931064045568/353124472183717888/unknown.png)

Any advice how to fix this issue at all ?

**Comment by StefH** [comment]
Thanks.

New version added to NuGet : https://www.nuget.org/packages/NETStandard.HttpListener/1.0.3
