### ISSUE TITLE
Problem with UWP HttpListener

### ISSUE THREAD

**Issue by trofimovps** [StefH/NETStandard.HttpListener#13]
Hello.
I tried to use your library on small UWP application, but it could not accept any request.
Even more - I tried example from NETStandard.HttpListener, but it behave the same (added server capabilities, but it did not help).

Could you check your example? And may be fix it or point me what am I doing wrong? (Checked on VS 2017 Professional/Community + Chrome)

**Comment by StefH** [comment]
I did also notice this. Maybe has something to do that the ports are not exposed by default on a UWP app?

**Comment by trofimovps** [comment]
Any way you are misleading people who are using this nuget :)

**Comment by StefH** [comment]
I will take a look.

**Comment by StefH** [comment]
Code works, however the port cannot be accessed.
I found some links, however no solution yet:


https://stackoverflow.com/questions/17833232/cannot-connect-to-localhost-in-windows-store-application
https://stackoverflow.com/questions/40474244/how-do-i-connect-to-a-windows-universal-app-streamsocket-from-a-console-applicat


https://msdn.microsoft.com/en-us/library/windows/apps/hh780593.aspx

`CheckNetIsolation.exe LoopbackExempt -s`

**Comment by StefH** [comment]
OK.

I did add a `WebView` which just accesses the http://localhost:18081 and that works fine.

For external access, I dont think that's possible on same PC.

See:
https://msdn.microsoft.com/en-us/library/windows/apps/hh780593

> Note  Loopback is permitted only for development purposes. Usage by a Windows Runtime app installed outside of Visual Studio is not permitted. Further, a Windows Runtime app can use an IP loopback only as the target address for a client network request. So a Windows Runtime app that uses a DatagramSocket or StreamSocketListener to listen on an IP loopback address is prevented from receiving any incoming packets.
