### ISSUE TITLE
Problem with whitespace encoding

### ISSUE THREAD

**Issue by trofimovps** [StefH/NETStandard.HttpListener#14]
White space is usually encoded as '+' (and plane plus symbol is wrapped in %2B).

Current decoder implementation is always expecting white space to be encoded in %20.

There is solution for this http://stackoverflow.com/questions/20268544/portable-class-library-pcl-version-of-httputility-parsequerystring (link taken from your lib)

**Comment by StefH** [comment]
Can you make a Pull Request for this?

**Comment by trofimovps** [comment]
It would be pullrequest for 1 line, something like this:

public static string UrlDecode(string s)
        {
            string result;
            s = s.Replace("+", "%20");
            while ((result = Uri.UnescapeDataString(s)) != s)
                s = result;
            return result;
        }

**Comment by StefH** [comment]
I will take a look tomorrow.

Also if you find more bugs, maybe it is better to bundle.

**Comment by StefH** [comment]
See https://www.nuget.org/packages/NETStandard.HttpListener/1.0.3.2

**Comment by trofimovps** [comment]
Hello.

                var value = HttpUtility.UrlDecode(valuePair.Value);
                values[valuePair.Key] = valuePair.Value;

You have managed to decode string, but still using encoded one.
