### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by mbp** [StefH/NETStandard.HttpListener#17]
HttpListener exists in .NET Core 2 / .NET Standard, so the description that it fills the void is not true.
It does however fill a different purpose in that it does not depend on http.sys on Windows, which can be useful.

Also, the provided sample in `README.md` does not compile:

![image](https://user-images.githubusercontent.com/77322/33930915-c50616ca-dfee-11e7-8f71-7045d7c731de.png)

**Comment by cherepets** [comment]
We had WebListener in Core 1 too so there always was an implementation from Microsoft but it was not crossplatform and less extendable.

About the code, I think the correct one would be like
`        if (context.Response.Method == HttpMethod.Get)
        { 
                await context.Response.WriteContentAsync("Hello from Server ...");
        }`

**Comment by mbp** [comment]
You actually also get an error `'HttpListener' is an ambiguous reference between 'System.Net.Http.HttpListener' and 'System.Net.HttpListener`

So the first line in the sample must be changed to:
```
var listener = new System.Net.Http.HttpListener(IPAddress.Parse("127.0.0.1"), 8081);
```

**Comment by StefH** [comment]
updated
