### ISSUE TITLE
UriBuilder doesn't parse Host header correctly

### ISSUE THREAD

**Issue by disrvptor** [StefH/NETStandard.HttpListener#18]
The following post shows the limitations of UriBuilder not respecting URI formatting.
https://social.msdn.microsoft.com/Forums/vstudio/en-US/995f4aca-3d22-4803-a7d9-f6a93723923c/uribuilder-does-not-add-default-http-scheme-if-source-uri-string-contains-port-number?forum=netfxbcl

Basically, HttpListenerRequest (line 52) takes the Host header and uses it to construct a URL. Unfortunately this fails because Host is something like "localhost:8080" and passing "localhost:8080/" to UriBuilder makes it look like the Scheme is "localhost" and the LocalPath is "8080/".

Ideally UriBuilder would behave correctly, but an interim solution may be detecting if the Host starts with "http://" and if not then prepending it.

Reference: https://github.com/StefH/NETStandard.HttpListener/blob/master/src/NETStandard.HttpListener/HttpListenerRequest.cs#L52

**Comment by StefH** [comment]
Implemented interim solution.

Use the new NuGet.
