### ISSUE TITLE
System.IO.IOException occurred

### ISSUE THREAD

**Issue by Jimmy062006** [StefH/NETStandard.HttpListener#2]
So I'm using this and its great accept I couldn't work out why it stopped running with no error on it.

I have try blocks around all my code accept I cannot catch this error.

```Message=Unable to write data to the transport connection: An established connection was aborted by the software in your host machine.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.Sockets.NetworkStream.<>c.<WriteAsync>b__59_0(Byte[] bufferArg, Int32 offsetArg, Int32 sizeArg, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state)
   at System.Net.Sockets.NetworkStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 size, CancellationToken cancellationToken)
   at System.IO.MemoryStream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.IO.Stream.CopyToAsync(Stream destination)
   at System.Net.Http.HttpListenerResponse.<SendMessage>d__26.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpListenerResponse.<Close>d__28.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()```

**Comment by StefH** [comment]
Please provide some more code samples.

**Comment by Jimmy062006** [comment]
The code is on the Opux github. I'll update with a link soon in on my mobile at the moment. You can search it though in the functions.cs file in the authweb method.

**Comment by Jimmy062006** [comment]
@StefH https://github.com/Jimmy062006/Opux/blob/master/src/Opux/Functions.cs#L176-L1287

**Comment by StefH** [comment]
Sorry, your code is way to complex to understand.

**Comment by Jimmy062006** [comment]
```cs
using System;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;

namespace HttpListener_Test
{
    class Program
    {
        public static void Main(string[] args)
        {
            MainAsync(args).GetAwaiter().GetResult();
            Console.ReadLine();
        }

        internal static async Task MainAsync(string[] args)
        {
            HttpListener listener = new HttpListener(IPAddress.Any, 8080);
            listener.Request += async (sender, context) =>
            {
                var request = context.Request;
                var response = context.Response;
                if (request.Method == HttpMethod.Get.ToString())
                {
                    await response.WriteContentAsync("<!doctype html>" +
                                    "<html>" +
                                    "<head>" +
                                    "    <title>HTTPListener Test</title>" +
                                    $" <p>{DateTime.Now}</p>" +
                                    "</html>");
                }
                response.Close();
            };
            listener.Start();
            Console.WriteLine("Starting Listener");
            await Task.CompletedTask;
        }
    }
}```

This code actually causes the same issue.

![error](https://cloud.githubusercontent.com/assets/4639349/24957879/3d70d094-1f85-11e7-9ddd-b49d0db19ef3.PNG)

**Comment by Jimmy062006** [comment]
You can actually replicate this with the example code.

```System.IO.IOException occurred
  HResult=0x80131620
  Message=Unable to write data to the transport connection: An established connection was aborted by the software in your host machine.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.Sockets.NetworkStream.<>c.<WriteAsync>b__59_0(Byte[] bufferArg, Int32 offsetArg, Int32 sizeArg, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state)
   at System.Net.Sockets.NetworkStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 size, CancellationToken cancellationToken)
   at System.IO.MemoryStream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpListenerResponse.<SendMessage>d__26.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpListenerResponse.<Close>d__28.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Inner Exception 1:
SocketException: An established connection was aborted by the software in your host machine
```

**Comment by Jimmy062006** [comment]
```cs
using System;
using System.Net;
using System.Net.Http;

namespace HttpListener_Test
{
    class Program
    {
        public static void Main(string[] args)
        {
            var listener = new HttpListener(IPAddress.Parse("127.0.0.1"), 8080);
            try
            {
                listener.Request += async (sender, context) => {
                    var request = context.Request;
                    var response = context.Response;
                    if (request.Method == HttpMethod.Get.ToString())
                    {
                        await response.WriteContentAsync($"Hello from Server at: {DateTime.Now}\r\n");
                    }
                    else
                    {
                        response.MethodNotAllowed();
                    }
                    // Close the HttpResponse to send it back to the client.
                    response.Close();
                };
                listener.Start();

                Console.WriteLine("Press any key to exit.");
                Console.ReadKey();
            }
            catch (Exception exc)
            {
                Console.WriteLine(exc.ToString());
            }
            finally
            {
                listener.Close();
            }
            Console.ReadLine();
        }
    }
}
```

**Comment by Jimmy062006** [comment]
its clear whats happening from that error though :)

Its trying to send data to a closed socket. I noticed there's no error handling for it.

**Comment by StefH** [comment]
Example:
```c#
using System;
using System.Net;
using System.Net.Http;

namespace TestConsoleApp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            int port = 18081;

            var listener = new HttpListener(IPAddress.Any, port);
            listener.Request += HandleRequest;
            listener.Start();

            bool isListening = listener.IsListening;
            Console.WriteLine("isListening = {0} at port {1}", isListening, port);

            Console.WriteLine("Press any key to stop listener");
            
            Console.ReadKey();
            listener.Close();
            listener.Dispose();
        }

        private static async void HandleRequest(object sender, HttpListenerRequestEventArgs e)
        {
            var request = e.Request;
            var response = e.Response;

            if (request.Method == HttpMethods.Get)
            {
                string content = @"<h2>Hello! What's your name?</h2>
                                <form method=""POST"" action=""/?test=2"">
                                    <input name=""name""></input>
                                    <button type=""submit"">Send</button>
                                </form>";

                await response.WriteContentAsync(MakeDocument(content));
            }
            else if (request.Method == HttpMethods.Post)
            {
                var param = request.RequestUri.ParseQueryParameters();

                var data = await request.ReadUrlEncodedContentAsync();
                var name = data["name"];

                string content = $"<h2>Hi, {name}! Nice to meet you.</h2>";

                await response.WriteContentAsync(MakeDocument(content));

                Console.WriteLine($"--> Hi, {name}! Nice to meet you.");
            }
            else
            {
                response.MethodNotAllowed();
            }

            response.Close();
        }

        private static string MakeDocument(object content)
        {
            return @"<html>
                        <head>
                            <title>Test</title>
                        </head>
                        <body>" +
                            content +
                        @"</body>
                    </html>";
        }
    }
}
```

**Comment by Jimmy062006** [comment]
Let me see if I can do it with that example then.

**Comment by Jimmy062006** [comment]
Same thing.

```System.IO.IOException occurred
  HResult=0x80131620
  Message=Unable to write data to the transport connection: An established connection was aborted by the software in your host machine.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.Sockets.NetworkStream.<>c.<WriteAsync>b__59_0(Byte[] bufferArg, Int32 offsetArg, Int32 sizeArg, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state)
   at System.Net.Sockets.NetworkStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 size, CancellationToken cancellationToken)
   at System.IO.MemoryStream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpListenerResponse.<SendMessage>d__26.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpListenerResponse.<Close>d__28.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Inner Exception 1:
SocketException: An established connection was aborted by the software in your host machine
```

**Comment by Jimmy062006** [comment]
It works until you reload the page before its sent the request. This will and does happen in he wild so clearly is an issue.

My App I made stops running without even logging this error I had to force the error by trying to reload the page ever 1 second and then opening it between 10 and 20 times.

**Comment by Jimmy062006** [comment]
I traced the error to the Close event as shown in this picture.

![error_located](https://cloud.githubusercontent.com/assets/4639349/24998619/ae8ca5c0-2032-11e7-9d8b-e9674ddf13cb.PNG)

I then wrapped it in a try block and wrote a debug output line to test it. It now continues to run without crashing but still debug logs the error using the test code you gave me.

Hope this helps.

```cs
        /// <summary>
        /// Closes this response and sends it.
        /// </summary>
        public async void Close()
        {
            try
            {
                await SendMessage();
            }
            catch (IOException ex)
            {
                Debug.WriteLine(ex.Message);
            }
            finally
            {
                CloseSocket();
            }
        }
```

If you want a pull request of think of something better please tell me 💃

**Comment by Jimmy062006** [comment]
Set Close back to normal and placed a try catch block around the offending code :)

```cs
        private async Task SendMessage()
        {
                var outputStream = OutputStream as MemoryStream;
                outputStream.Seek(0, SeekOrigin.Begin);

                var socketStream = _client.GetOutputStream();

                string header = $"{Version} {StatusCode} {ReasonPhrase}\r\n" +
                                Headers +
                                $"Content-Length: {outputStream.Length}\r\n" +
                                "\r\n";
                byte[] headerArray = Encoding.UTF8.GetBytes(header);

                await socketStream.WriteAsync(headerArray, 0, headerArray.Length);
            try
            {
                await outputStream.CopyToAsync(socketStream);
            }
            catch (IOException ex)
            {
                Debug.WriteLine(ex.Message);
            }
            finally
            {
                await socketStream.FlushAsync();
            }
        }
```

**Comment by brswan** [comment]
I'm also getting this issue when a user navigates away from a web pages and my server is still trying to send back data.

version: 1.0.3.5

03-11 15:29:19.038 I/mono-stdout(12541): System.IO.IOException: Unable to write data to the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
03-11 15:29:19.038 I/mono-stdout(12541):   at System.Net.Sockets.Socket.EndSend (System.IAsyncResult asyncResult) [0x00012] in <fb6d78e506844b3b96d5b35aa047fbbd>:0 
03-11 15:29:19.038 I/mono-stdout(12541):   at System.Net.Sockets.NetworkStream.EndWrite (System.IAsyncResult asyncResult) [0x00057] in <fb6d78e506844b3b96d5b35aa047fbbd>:0 
03-11 15:29:19.038 I/mono-stdout(12541):    --- End of inner exception stack trace ---
03-11 15:29:19.038 I/mono-stdout(12541):   at System.Net.Sockets.NetworkStream.EndWrite (System.IAsyncResult asyncResult) [0x0009b] in <fb6d78e506844b3b96d5b35aa047fbbd>:0 
03-11 15:29:19.038 I/mono-stdout(12541):   at System.IO.Stream+<>c.<BeginEndWriteAsync>b__53_1 (System.IO.Stream stream, System.IAsyncResult asyncResult) [0x00000] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
03-11 15:29:19.038 I/mono-stdout(12541):   at (wrapper delegate-invoke) System.Func`3[System.IO.Stream,System.IAsyncResult,System.Threading.Tasks.VoidTaskResult].invoke_TResult_T1_T2(System.IO.Stream,System.IAsyncResult)
03-11 15:29:19.038 I/mono-stdout(12541):   at System.Threading.Tasks.TaskFactory`1+FromAsyncTrimPromise`1[TResult,TInstance].Complete (TInstance thisRef, System.Func`3[T1,T2,TResult] endMethod, System.IAsyncResult asyncResult, System.Boolean requiresSynchronization) [0x00000] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
03-11 15:29:19.038 I/mono-stdout(12541): --- End of stack trace from previous location where exception was thrown ---
03-11 15:29:19.038 I/mono-stdout(12541):   at System.Net.Http.HttpListenerResponse+<SendMessage>d__27.MoveNext () [0x001a0] in <604997c6a1ba450394e87a11d242d541>:0 
03-11 15:29:19.038 I/mono-stdout(12541): --- End of stack trace from previous location where exception was thrown ---
03-11 15:29:19.038 I/mono-stdout(12541):   at System.Net.Http.HttpListenerResponse+<SendMessage>d__27.MoveNext () [0x00233] in <604997c6a1ba450394e87a11d242d541>:0 
03-11 15:29:19.038 I/mono-stdout(12541): --- End of stack trace from previous location where exception was thrown ---
03-11 15:29:19.038 I/mono-stdout(12541):   at System.Net.Http.HttpListenerResponse+<Close>d__29.MoveNext () [0x00062] in <604997c6a1ba450394e87a11d242d541>:0 
03-11 15:29:19.038 I/mono-stdout(12541): --- End of stack trace from previous location where exception was thrown ---
03-11 15:29:19.038 I/mono-stdout(12541):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1 (System.Object state) [0x00000] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
03-11 15:29:19.038 I/mono-stdout(12541):   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x00007] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
03-11 15:29:19.038 I/mono-stdout(12541):   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
03-11 15:29:19.038 I/mono-stdout(12541):   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
03-11 15:29:19.038 I/mono-stdout(12541):   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00021] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
03-11 15:29:19.038 I/mono-stdout(12541):   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
03-11 15:29:19.038 I/mono-stdout(12541):   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
03-11 15:29:19.068 W/AppCenterCrashes(12541): HandledError : property 'Exception' : property value cannot be longer than 125 characters. Property value will be truncated.
03-11 15:29:19.088 E/AppCenterCrashes(12541): Unhandled Exception from source=AppDomain
03-11 15:29:19.088 E/AppCenterCrashes(12541): System.IO.IOException: Unable to write data to the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
03-11 15:29:19.088 E/AppCenterCrashes(12541):   at System.Net.Sockets.Socket.EndSend (System.IAsyncResult asyncResult) [0x00012] in <fb6d78e506844b3b96d5b35aa047fbbd>:0 
03-11 15:29:19.088 E/AppCenterCrashes(12541):   at System.Net.Sockets.NetworkStream.EndWrite (System.IAsyncResult asyncResult) [0x00057] in <fb6d78e506844b3b96d5b35aa047fbbd>:0 
03-11 15:29:19.088 E/AppCenterCrashes(12541):    --- End of inner exception stack trace ---
03-11 15:29:19.088 E/AppCenterCrashes(12541):   at System.Net.Sockets.NetworkStream.EndWrite (System.IAsyncResult asyncResult) [0x0009b] in <fb6d78e506844b3b96d5b35aa047fbbd>:0 
03-11 15:29:19.088 E/AppCenterCrashes(12541):   at System.IO.Stream+<>c.<BeginEndWriteAsync>b__53_1 (System.IO.Stream stream, System.IAsyncResult asyncResult) [0x00000] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
03-11 15:29:19.088 E/AppCenterCrashes(12541):   at (wrapper delegate-invoke) System.Func`3[System.IO.Stream,System.IAsyncResult,System.Threading.Tasks.VoidTaskResult].invoke_TResult_T1_T2(System.IO.Stream,System.IAsyncResult)
03-11 15:29:19.088 E/AppCenterCrashes(12541):   at System.Threading.Tasks.TaskFactory`1+FromAsyncTrimPromise`1[TResult,TInstance].Complete (TInstance thisRef, System.Func`3[T1,T2,TResult] endMethod, System.IAsyncResult asyncResult, System.Boolean requiresSynchronization) [0x00000] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
03-11 15:29:19.088 E/AppCenterCrashes(12541): --- End of stack trace from previous location where exception was thrown ---
03-11 15:29:19.088 E/AppCenterCrashes(12541):   at System.Net.Http.HttpListenerResponse+<SendMessage>d__27.MoveNext () [0x001a0] in <604997c6a1ba450394e87a11d242d541>:0 
03-11 15:29:19.088 E/AppCenterCrashes(12541): --- End of stack trace from previous location where exception was thrown ---
03-11 15:29:19.088 E/AppCenterCrashes(12541):   at System.Net.Http.HttpListenerResponse+<SendMessage>d__27.MoveNext () [0x00233] in <604997c6a1ba450394e87a11d242d541>:0 
03-11 15:29:19.088 E/AppCenterCrashes(12541): --- End of stack trace from previous location where exception was thrown ---
03-11 15:29:19.088 E/AppCenterCrashes(12541):   at System.Net.Http.HttpListenerResponse+<Close>d__29.MoveNext () [0x00062] in <604997c6a1ba450394e87a11d242d541>:0 
03-11 15:29:19.088 E/AppCenterCrashes(12541): --- End of stack trace from previous location where exception was thrown ---
