### ISSUE TITLE
HTTP headers should be case-insensetive

### ISSUE THREAD

**Issue by cherepets** [StefH/NETStandard.HttpListener#5]
Please take a look at rfc:
http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

I had a client side code with "content-length" header. On the server side `Heraders.ContentLength` property returned -1 (why not 0?) and `char[] buffer = new char[contentLength]` failed with exception `Cannot create an array with a negative size`.

**Comment by cherepets** [comment]
Create a fork and made pull request:
https://github.com/StefH/NETStandard.HttpListener/pull/6

**Comment by StefH** [comment]
Thanks.
