### ISSUE TITLE
More HTTP methods are required

### ISSUE THREAD

**Issue by cherepets** [StefH/NETStandard.HttpListener#7]
HTTP methods like OPTIONS, HEAD, TRACE and CONNECT are a part of the rfc so it's good to have them.
In some cases (mostly jsonp) Chrome web browser can replace POST with OPTIONS so we definitely need to allow OPTIONS to have content.
As far as I know custom methods also can have content.

**Comment by cherepets** [comment]
Created a merge request for this:
https://github.com/StefH/NETStandard.HttpListener/pull/8

**Comment by StefH** [comment]
Thanks.
